Use curl insteal of ruby Net:HTTP
```
  60) config/countries.yml https://www.apple.com/la/support/systemstatus/ is available
      Failure/Error: response = http.head("/#{country}/support/systemstatus/")

      NoMethodError:
        Failed to open TCP connection to www.apple.com:443 (undefined method `[]' for nil:NilClass)
      # ./spec/config/countries_spec.rb:10:in `block (3 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # NoMethodError:
      #   undefined method `[]' for nil:NilClass
      #   ./vendor/bundle/ruby/2.5.0/gems/backports-2.8.2/lib/backports/tools.rb:269:in `combine_mode_and_option'
```